apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dev-app.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "dev-app.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "dev-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "dev-app.name" . }}
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: landing-page
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: landing-page
          configMap:
            name: {{ include "dev-app.name" . }}-content
