apiVersion: v1
kind: Service
metadata:
  name: {{ include "dev-app.name" . }}-svc
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ include "dev-app.name" . }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
