apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.name" . }}-api
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "backend.name" . }}-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
