apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.name" . }}-redis
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "backend.name" . }}-redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
