apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: click-lab
  namespace: argo-cd-labs
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - list:
        elements:
          - environment: dev
            namespace: click-lab-dev
            targetRevision: develop
          - environment: prod
            namespace: click-lab-prod
            targetRevision: main

  template:
    metadata:
      name: "click-lab-{{ .environment }}"
      labels:
        app.kubernetes.io/part-of: click-lab
        environment: "{{ .environment }}"
    spec:
      project: default
      sources:
        - repoURL: https://github.com/rafaelsvieira/argo-labs
          targetRevision: "{{ .targetRevision }}"
          path: "apps/backend/"
          helm:
            valueFiles:
            - "values-{{ .environment }}.yaml"
        - repoURL: https://github.com/rafaelsvieira/argo-labs
          targetRevision: "{{ .targetRevision }}"
          path: "apps/frontend/"
          helm:
            valueFiles:
            - "values-{{ .environment }}.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .namespace }}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true
