apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontend.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "frontend.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "frontend.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "frontend.name" . }}
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: html
          configMap:
            name: {{ include "frontend.name" . }}-content
        - name: nginx-config
          configMap:
            name: {{ include "frontend.name" . }}-nginx
